apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-mcp-config
  labels:
    app: gateway-mcp
data:
  backends.json: |
    {
      "graphrag-mcp": "http://svc-graphrag-mcp:5001/sse"
    }
  GUARDRAIL_NG_WORDS: "うんこ,デブ,ブサイク,ignore previous instructions,これまでの指示を無視"
  GUARDRAIL_SECRET_WORDS: "社外秘,機密,パスワード,SECRET_PASSWORD"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-mcp
  labels:
    app: gateway-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-mcp
  template:
    metadata:
      labels:
        app: gateway-mcp
    spec:
      containers:
        - name: gateway-mcp
          image: developeronizuka/gateway-mcp:1.0.1
          #imagePullPolicy: Always
          ports:
            - containerPort: 5001
              name: http-sse
          env:
            - name: PORT
              value: "5001"
            - name: BACKEND_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: gateway-mcp-config
                  key: backends.json
            - name: GUARDRAIL_NG_WORDS
              valueFrom:
                configMapKeyRef:
                  name: gateway-mcp-config
                  key: GUARDRAIL_NG_WORDS
            - name: GUARDRAIL_SECRET_WORDS
              valueFrom:
                configMapKeyRef:
                  name: gateway-mcp-config
                  key: GUARDRAIL_SECRET_WORDS
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: svc-gateway-mcp
  labels:
    app: gateway-mcp
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http-sse
  selector:
    app: gateway-mcp
